name: 'Bump Version'
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
  packages: write
jobs:
  bump-version:
    name: 'Bump Version on dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.ref }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json


